baseURL = 'https://tux24.xyz/'
languageCode = 'zh-Hant'
title = "tux24 的個人網站"
theme = "hugo-coder"
defaultcontentlanguage = 'zh-Hant'
#baseurl = "http://www.example.com"
#title = "johndoe"
#theme = "hugo-coder"
#languagecode = "en"
#defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[service]

[markup.highlight]
style = "doom-one2"

[params]
  author = "tux24"
  info = "想認識我的話，就透過這個網站吧"
  description = "tux24 的個人網站"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "images/favicon.svg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tux24xyz/"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 2
  url = "https://tux24.xyz/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "文章"
  weight = 1
  url  = "articles/"
[[menu.main]]
  name = "關於"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "近況"
  weight = 3
  url = "now/"
[[menu.main]]
  name = "連結"
  weight = 4
  url = "links/"
[[menu.main]]
  name = "工具"
  weight = 5
  url = "use/"
[[menu.main]]
  name = "標籤"
  weight = 6
  url = "tags/"
[[menu.main]]
  name = "聯絡我"
  weight = 7
  url = "contact/"


